
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from edu.harvard.i2b2.crc.ejb.PdoQueryBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Local interface for querytool.PdoQuery
 */
public interface PdoQueryLocal 
extends javax.ejb.EJBLocalObject {
    edu.harvard.i2b2.crc.datavo.pdo.query.PatientDataResponseType getPlainPatientData(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, edu.harvard.i2b2.crc.datavo.pdo.query.GetPDOFromInputListRequestType getPDOFromInputListReqType, java.lang.String requestXml) throws edu.harvard.i2b2.common.exception.I2B2Exception;
    java.util.List getPDOTemplate(java.lang.String dimensionTableName, edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, boolean tablePDOFlag) throws edu.harvard.i2b2.common.exception.I2B2Exception;
    edu.harvard.i2b2.crc.datavo.pdo.PatientDataType getObservationFactByPrimaryKey(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, edu.harvard.i2b2.crc.datavo.pdo.query.GetObservationFactByPrimaryKeyRequestType getObservationFactByPrimaryKeyRequestType) throws edu.harvard.i2b2.common.exception.I2B2Exception;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
