
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from edu.harvard.i2b2.crc.ejb.PdoQueryBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Local-Home interface for querytool.PdoQuery
 */
public interface PdoQueryLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/querytool/PdoQueryLocal";
    public static final String JNDI_NAME = "querytool/PdoQueryLocal";

    edu.harvard.i2b2.crc.ejb.PdoQueryLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
