
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from edu.harvard.i2b2.crc.ejb.PdoQueryBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Remote interface for querytool.PdoQuery
 */
public interface PdoQueryRemote 
extends javax.ejb.EJBObject {
    edu.harvard.i2b2.crc.datavo.pdo.query.PatientDataResponseType getPlainPatientData(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, edu.harvard.i2b2.crc.datavo.pdo.query.GetPDOFromInputListRequestType getPDOFromInputListReqType, java.lang.String requestXml) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    java.util.List getPDOTemplate(java.lang.String dimensionTableName, edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, boolean tablePDOFlag) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.pdo.PatientDataType getObservationFactByPrimaryKey(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, edu.harvard.i2b2.crc.datavo.pdo.query.GetObservationFactByPrimaryKeyRequestType getObservationFactByPrimaryKeyRequestType) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
