
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryRunBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Remote interface for querytool.QueryRun
 */
public interface QueryRunRemote 
extends javax.ejb.EJBObject {
    edu.harvard.i2b2.crc.datavo.setfinder.query.InstanceResponseType getQueryInstanceFromMasterId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, edu.harvard.i2b2.crc.datavo.setfinder.query.MasterRequestType masterRequestType) throws edu.harvard.i2b2.common.exception.I2B2DAOException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
