
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryRunBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Local-Home interface for querytool.QueryRun
 */
public interface QueryRunLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/querytool/QueryRunLocal";
    public static final String JNDI_NAME = "querytool/QueryRunLocal";

    edu.harvard.i2b2.crc.ejb.QueryRunLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
