
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryManagerBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Remote interface for querytool.QueryManager
 */
public interface QueryManagerRemote 
extends javax.ejb.EJBObject {
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterInstanceResultResponseType processQuery(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String xmlRequest) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.InstanceResultResponseType runQueryMaster(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, java.lang.String masterId, long timeout) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    java.lang.String getResponseXML(java.lang.String sessionId) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
