
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryManagerBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Local interface for querytool.QueryManager
 */
public interface QueryManagerLocal 
extends javax.ejb.EJBLocalObject {
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterInstanceResultResponseType processQuery(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String xmlRequest) throws edu.harvard.i2b2.common.exception.I2B2Exception;
    edu.harvard.i2b2.crc.datavo.setfinder.query.InstanceResultResponseType runQueryMaster(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, java.lang.String masterId, long timeout) throws edu.harvard.i2b2.common.exception.I2B2Exception;
    java.lang.String getResponseXML(java.lang.String sessionId);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
