
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteHomeInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryInfoBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Home interface for querytool.QueryInfo
 */
public interface QueryInfoRemoteHome
extends javax.ejb.EJBHome {
    public static final String COMP_NAME = "java:comp/env/ejb/querytool/QueryInfoRemote";
    public static final String JNDI_NAME = "querytool/QueryInfoRemote";

    edu.harvard.i2b2.crc.ejb.QueryInfoRemote create() throws javax.ejb.CreateException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
