
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryResultBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Remote interface for querytool.QueryResult
 */
public interface QueryResultRemote 
extends javax.ejb.EJBObject {
    edu.harvard.i2b2.crc.datavo.setfinder.query.ResultResponseType getResultInstanceFromQueryInstanceId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, java.lang.String queryInstanceId) throws edu.harvard.i2b2.common.exception.I2B2DAOException, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.CrcXmlResultResponseType getXmlResultFromResultInstanceId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String queryResultInstanceId) throws edu.harvard.i2b2.common.exception.I2B2DAOException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
