
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryResultBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Local interface for querytool.QueryResult
 */
public interface QueryResultLocal 
extends javax.ejb.EJBLocalObject {
    edu.harvard.i2b2.crc.datavo.setfinder.query.ResultResponseType getResultInstanceFromQueryInstanceId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, java.lang.String queryInstanceId) throws edu.harvard.i2b2.common.exception.I2B2DAOException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.CrcXmlResultResponseType getXmlResultFromResultInstanceId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String queryResultInstanceId) throws edu.harvard.i2b2.common.exception.I2B2DAOException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
