
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryInfoBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Remote interface for querytool.QueryInfo
 */
public interface QueryInfoRemote 
extends javax.ejb.EJBObject {
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterResponseType getQueryMasterListFromUserId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, edu.harvard.i2b2.crc.datavo.setfinder.query.UserRequestType userRequestType) throws edu.harvard.i2b2.common.exception.I2B2DAOException, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterResponseType getQueryMasterListFromGroupId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, edu.harvard.i2b2.crc.datavo.setfinder.query.UserRequestType userRequestType) throws edu.harvard.i2b2.common.exception.I2B2DAOException, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterResponseType getRequestXmlFromMasterId(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, edu.harvard.i2b2.crc.datavo.setfinder.query.MasterRequestType masterRequestType) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterResponseType deleteQueryMaster(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, java.lang.String masterId) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.MasterResponseType renameQueryMaster(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String userId, java.lang.String masterId, java.lang.String queryNewName) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.ResultResponseType updateResultInstanceDescription(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String resultInstanceId, java.lang.String newDescription) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.InstanceResultResponseType cancelQueryInstance(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup, java.lang.String instanceId) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
    edu.harvard.i2b2.crc.datavo.setfinder.query.ResultTypeResponseType getAllResultType(edu.harvard.i2b2.crc.datavo.db.DataSourceLookup dataSourceLookup) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
