
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from edu.harvard.i2b2.crc.ejb.QueryResultBean
package edu.harvard.i2b2.crc.ejb;

/**
 * Local-Home interface for querytool.QueryResult
 */
public interface QueryResultLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/querytool/QueryResultLocal";
    public static final String JNDI_NAME = "querytool/QueryResultLocal";

    edu.harvard.i2b2.crc.ejb.QueryResultLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
