DROP TABLE IF EXISTS I2B2;
DROP TABLE IF EXISTS BIRN;
DROP TABLE IF EXISTS TABLE_ACCESS;
DROP TABLE IF EXISTS SCHEMES;
DROP TABLE IF EXISTS CUSTOM_META;
DROP TABLE IF EXISTS ONT_PROCESS_STATUS;
DROP sequence IF EXISTS ONT_SQ_PS_PRID;