INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Stage\\0\\', 'TNM:STAGE0', 'Carcinoma in situ', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Stage\\I\\', 'TNM:STAGEI', 'Cancer is localized', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Stage\\II\\', 'TNM:STAGEII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Stage\\III\\', 'TNM:STAGEIII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Stage\\IV\\', 'TNM:STAGEIV', 'Metastasized to distant lymph nodes and / organs', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\', 'TNM:TUMOR', 'TNM Staging, Tumor Rating', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\T0\\', 'TNM:T0', 'No evidence of primary tumor', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\T1\\', 'TNM:T1', 'Tumor small in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\T2\\', 'TNM:T2', 'Tumor medium in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\T3\\', 'TNM:T3', 'Tumor large in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\T4\\', 'TNM:T4', 'Tumor very large in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\Tis\\', 'TNM:Tis', 'Carcinoma in situ', 'CIS; abnormal cells present but have not spread to neighboring tissue.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Tumor\\TX\\', 'TNM:TX', 'Primary tumor cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Admit Diagnosis\\', '0', 'Admit Diagnosis', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Metastisis\\', 'TNM:METASTISIS', 'TNM Staging, Distant Metastisis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Metastisis\\M0\\', 'TNM:M0', 'TNM Staging, No distant metastasis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Metastisis\\M1\\', 'TNM:M1', 'TNM Staging, Distant metastasis is present', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Metastisis\\M1\\M1a\\', 'TNM:M1a', 'TNM Staging, Metastasized to other lung; Malignant pleural effusion; or Malignant pericardial effusion', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Metastisis\\M1\\M1b\\', 'TNM:M1b', 'TNM Staging, Metastasized to distant lymph nodes and / organs', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Nodes\\', 'TNM:NODES', 'TNM Staging, Regional lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Nodes\\N0\\', 'TNM:N0', 'TNM Staging, No regional lymph node involvement', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Nodes\\N1\\', 'TNM:N1', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes within the lung and/or the hilar lymph nodes. Affected lymph nodes are on the same side as the primary tumor.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Nodes\\N2\\', 'TNM:N2', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes around the carina or in the mediastinum. Affected lymph nodes are on the same side as the primary tumor.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Nodes\\N3\\', 'TNM:N3', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes near the collarbone on either side, and/or spread to hilar or mediastinal lymph nodes on the side opposite the primary tumor', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Nodes\\NX\\', 'TNM:NX', 'TNM Staging, Regional lymph nodes cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\', 'TNM:STAGE', 'TNM Staging, Stage Classification', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\0\\', 'TNM:STAGE0', 'Carcinoma in situ', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\I\\', 'TNM:STAGEI', 'Cancer is localized', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\I\\IA\\', 'TNM:STAGEIA', 'Cancer is localized; tumor is no larger than 3 cm; No involvement of lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\I\\IB\\', 'TNM:STAGEIB', 'Cancer is localized; tumor is between 3 and 5 cm; No involvement of lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\II\\', 'TNM:STAGEII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\II\\IIA\\', 'TNM:STAGEIIA', 'Cancer is localized; tumor is greater than 3 cm; Local lymph nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\II\\IIB\\', 'TNM:STAGEIIB', 'Cancer is localized; tumor is greater than 5 cm; Local lymph nodes may be involved; Multiple nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\III\\', 'TNM:STAGEIII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\III\\IIB\\', 'TNM:STAGEIIIB', 'Cancer is localized;  tumor may have grown into surrounding structures; Regional lymph nodes may be involved; Multiple nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\III\\IIIA\\', 'TNM:STAGEIIIA', 'Cancer is localized; tumor may have grown into surrounding structures; Regional lymph nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\IV\\', 'TNM:STAGEIV', 'Metastasized to distant lymph nodes and / organs', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Stage\\Occult\\', 'TNM:STAGE0', 'Cancer found in lung fluids but its location can''t be determined', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\', 'TNM:TUMOR', 'TNM Staging, Tumor Rating', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T0\\', 'TNM:T0', 'No evidence of primary tumor', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T1\\', 'TNM:T1', 'Tumor no greater than 3 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T1\\T1a\\', 'TNM:T1a', 'Tumor no greater than 2 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T1\\T1b\\', 'TNM:T1b', 'Tumor greater than 2 cm but less than 3 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T2\\', 'TNM:T2', 'Tumor between 3  and 7 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T2\\T2a\\', 'TNM:T2a', 'Tumor no greater than 5 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T2\\T2b\\', 'TNM:T2b', 'Tumor greater than 5 cm but less than 7 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T3\\', 'TNM:T3', 'Tumor greater than 7 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\T4\\', 'TNM:T4', 'Tumor grown into other areas or multiple nodules', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\Tis\\', 'TNM:Tis', 'Carcinoma in situ', 'CIS; abnormal cells present but have not spread to neighboring tissue.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Lung\\TNM\\Tumor\\TX\\', 'TNM:TX', 'Primary tumor cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Medication\\Dose\\', 'MED:DOSE', 'Medication Dose', NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Medication\\Frequency\\', 'MED:FREQ', 'Medication Frequency', NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Medication\\Route\\', 'MED:ROUTE', 'Medication Route', NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Principle Diagnosis\\', '1', 'Principle Diagnosis', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Secondary Diagnosis\\', '2', 'Secondary Diagnosis', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Mild To Mod\\', 'SNO:371923003', 'Severity: Mild to moderate', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Mild\\', 'SNO:255604002', 'Severity: Mild', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Moderate To Severe\\', 'SNO:371924009', 'Severity: Moderate to severe', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Moderate\\', 'SNO:6736007', 'Severity: Moderate', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Severe\\', 'SNO:24484000', 'Severity: Severe', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Severe\\Fatal\\', 'SNO:399166001', 'Severity: Fatal', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\Severity\\Severe\\Type I Hypersensitivity\\', 'SNO:264774001', 'Severity: Type I Hypersensitivity', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Metastisis\\', 'TNM:METASTISIS', 'TNM Staging, Distant Metastisis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Metastisis\\M0\\', 'TNM:M0', 'TNM Staging, No distant metastasis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Metastisis\\M1\\', 'TNM:M1', 'TNM Staging, Distant metastasis is present', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Metastisis\\MX\\', 'TNM:MX', 'TNM Staging, Distant metastasis cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Nodes\\', 'TNM:NODES', 'TNM Staging, Regional lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Nodes\\N0\\', 'TNM:N0', 'TNM Staging, No regional lymph node involvement', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Nodes\\N1\\', 'TNM:N1', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Nodes\\N2\\', 'TNM:N2', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Nodes\\N3\\', 'TNM:N3', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Nodes\\NX\\', 'TNM:NX', 'TNM Staging, Regional lymph nodes cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES(E'\\TNM\\Stage\\', 'TNM:STAGE', 'TNM Staging, Stage Classification', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
