
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from edu.harvard.i2b2.crc.loader.ejb.fr.FRBean
package edu.harvard.i2b2.crc.loader.ejb.fr;

/**
 * Remote interface for ejb.crc.loader.frbean
 */
public interface FRBeanRemote 
extends javax.ejb.EJBObject {
    java.lang.String createClient(int uploadId, edu.harvard.i2b2.crc.loader.datavo.loader.query.DataListType dataListType, edu.harvard.i2b2.crc.loader.datavo.i2b2message.SecurityType securityType, java.lang.String projectId, java.lang.String fileSystemDefaultStorageResource) throws edu.harvard.i2b2.common.exception.I2B2Exception, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
