
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteHomeInterfacePlugin from edu.harvard.i2b2.crc.loader.ejb.fr.FRBean
package edu.harvard.i2b2.crc.loader.ejb.fr;

/**
 * Home interface for ejb.crc.loader.frbean
 */
public interface FRRemoteHome
extends javax.ejb.EJBHome {
    public static final String COMP_NAME = "java:comp/env/ejb/ejb/crc/loader/frbeanRemote";
    public static final String JNDI_NAME = "ejb/crc/loader/frbeanRemote";

    edu.harvard.i2b2.crc.loader.ejb.fr.FRBeanRemote create() throws javax.ejb.CreateException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
