--*********************************************************
--         ORACLE SCRIPT TO CREATE DATA TABLES
--           SNM - 8/19/2008
--**********************************************************

-----------------------------------------------------------------------------------------
-- create ENCOUNTER_MAPPING table with clustered PK on ENCOUNTER_IDE, ENCOUNTER_IDE_SOURCE 
-----------------------------------------------------------------------------------------

CREATE TABLE ENCOUNTER_MAPPING ( 
    ENCOUNTER_IDE       	VARCHAR(200) NOT NULL,
    ENCOUNTER_IDE_SOURCE	VARCHAR(50) NOT NULL,
    ENCOUNTER_NUM       	NUMERIC(38,0) NOT NULL,
    PATIENT_IDE         	VARCHAR(200),
    PATIENT_IDE_SOURCE  	VARCHAR(50),
    ENCOUNTER_IDE_STATUS	VARCHAR(50),
    UPLOAD_DATE         	TIMESTAMP WITHOUT TIME ZONE,
    UPDATE_DATE             TIMESTAMP WITHOUT TIME ZONE,
    DOWNLOAD_DATE       	TIMESTAMP WITHOUT TIME ZONE,
	IMPORT_DATE			    TIMESTAMP WITHOUT TIME ZONE,
    SOURCESYSTEM_CD     	VARCHAR(50),
	UPLOAD_ID           	NUMERIC(38,0),
    CONSTRAINT ENCOUNTER_MAPPING_PK PRIMARY KEY(ENCOUNTER_IDE,ENCOUNTER_IDE_SOURCE)
 )
;
CREATE INDEX EM_UPLOADID_IDX ON ENCOUNTER_MAPPING(UPLOAD_ID)
;
CREATE  INDEX EM_IDX_ENCPATH ON ENCOUNTER_MAPPING(ENCOUNTER_IDE,ENCOUNTER_IDE_SOURCE,PATIENT_IDE,PATIENT_IDE_SOURCE,ENCOUNTER_NUM )
;
CREATE INDEX EM_ENCNUM_IDX ON ENCOUNTER_MAPPING(ENCOUNTER_NUM)
;



-------------------------------------------------------------------------------------
-- create PATIENT_MAPPING table with clustered PK on PATIENT_IDE, PATIENT_IDE_SOURCE
-------------------------------------------------------------------------------------

CREATE TABLE PATIENT_MAPPING ( 
    PATIENT_IDE       	VARCHAR(200) NOT NULL,
    PATIENT_IDE_SOURCE	VARCHAR(50) NOT NULL,
    PATIENT_NUM       	NUMERIC(38,0) NOT NULL,
    PATIENT_IDE_STATUS	VARCHAR(50),
    UPLOAD_DATE       	TIMESTAMP WITHOUT TIME ZONE,
    UPDATE_DATE         TIMESTAMP WITHOUT TIME ZONE,
    DOWNLOAD_DATE     	TIMESTAMP WITHOUT TIME ZONE,
    IMPORT_DATE			TIMESTAMP WITHOUT TIME ZONE,
    SOURCESYSTEM_CD   	VARCHAR(50),
    UPLOAD_ID         	NUMERIC(38,0),
    CONSTRAINT PATIENT_MAPPING_PK PRIMARY KEY(PATIENT_IDE,PATIENT_IDE_SOURCE)
 )
;
CREATE INDEX PM_UPLOADID_IDX ON PATIENT_MAPPING(UPLOAD_ID)
;
CREATE INDEX PM_PATNUM_IDX ON PATIENT_MAPPING(PATIENT_NUM)
;
CREATE INDEX PM_ENCPNUM_IDX ON 
PATIENT_MAPPING(PATIENT_IDE,PATIENT_IDE_SOURCE,PATIENT_NUM) ;

------------------------------------------------------------------------------
-- create CODE_LOOKUP table with clustered PK on TABLE_CD, COLUMN_CD, CODE_CD 
------------------------------------------------------------------------------

CREATE TABLE CODE_LOOKUP ( 
	TABLE_CD            VARCHAR(100) NOT NULL,
	COLUMN_CD           VARCHAR(100) NOT NULL,
	CODE_CD             VARCHAR(50) NOT NULL,
	NAME_CHAR           VARCHAR(650) NULL,
	LOOKUP_BLOB			TEXT,
    UPLOAD_DATE       	TIMESTAMP WITHOUT TIME ZONE NULL,
    UPDATE_DATE     	TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE   	TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE     	TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD 	VARCHAR(50) NULL,
	UPLOAD_ID       	NUMERIC(38,0) NULL,
    CONSTRAINT CODE_LOOKUP_PK PRIMARY KEY(TABLE_CD,COLUMN_CD,CODE_CD)
	)
;
-- add index on name_char field 
CREATE INDEX CL_IDX_NAME_CHAR ON CODE_LOOKUP(NAME_CHAR)
;
CREATE INDEX CL_IDX_UPLOADID ON CODE_LOOKUP(UPLOAD_ID)
;



--------------------------------------------------------------------
-- create CONCEPT_DIMENSION table with clustered PK on CONCEPT_PATH 
--------------------------------------------------------------------

CREATE TABLE CONCEPT_DIMENSION ( 
	CONCEPT_PATH    	VARCHAR(700) NOT NULL,
	CONCEPT_CD          VARCHAR(50) NOT NULL,
	NAME_CHAR       	VARCHAR(2000) NULL,
	CONCEPT_BLOB        TEXT NULL,
	UPDATE_DATE         TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE       TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE         TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD     VARCHAR(50) NULL,
	UPLOAD_ID       	NUMERIC(38,0) NULL,
    CONSTRAINT CONCEPT_DIMENSION_PK PRIMARY KEY(CONCEPT_PATH)
	)
;	
CREATE INDEX CD_UPLOADID_IDX ON CONCEPT_DIMENSION(UPLOAD_ID)
;



----------------------------------------------------------------------------------
--        create OBSERVATION_FACT table with NONclustered PK on
-- ENCOUNTER_NUM, CONCEPT_CD, PROVIDER_ID, START_DATE, MODIFIER_CD, INSTANCE_NUM 
----------------------------------------------------------------------------------

CREATE TABLE OBSERVATION_FACT (
	ENCOUNTER_NUM   	NUMERIC(38,0) NOT NULL,
	PATIENT_NUM     	NUMERIC(38,0) NOT NULL,
	CONCEPT_CD      	VARCHAR(50) NOT NULL,
	PROVIDER_ID     	VARCHAR(50) NOT NULL,
	START_DATE      	TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	MODIFIER_CD     	VARCHAR(100) NOT NULL,
	INSTANCE_NUM	    NUMERIC(18,0) NOT NULL,
	VALTYPE_CD      	VARCHAR(50) NULL,
	TVAL_CHAR       	VARCHAR(255) NULL,
	NVAL_NUM        	NUMERIC(18,5) NULL,
	VALUEFLAG_CD    	VARCHAR(50) NULL,
	QUANTITY_NUM    	NUMERIC(18,5) NULL,
	UNITS_CD        	VARCHAR(50) NULL,
	END_DATE        	TIMESTAMP WITHOUT TIME ZONE NULL,
	LOCATION_CD     	VARCHAR(50) NULL,
	OBSERVATION_BLOB	TEXT NULL,
	CONFIDENCE_NUM  	NUMERIC(18,5) NULL,
	UPDATE_DATE     	TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE   	TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE     	TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD 	VARCHAR(50) NULL,
	UPLOAD_ID       	NUMERIC(38,0) NULL, 
    CONSTRAINT OBSERVATION_FACT_PK PRIMARY KEY(ENCOUNTER_NUM,CONCEPT_CD,PROVIDER_ID,START_DATE,MODIFIER_CD,INSTANCE_NUM)
)
;

CREATE INDEX FACT_NOLOB ON OBSERVATION_FACT
(
	PATIENT_NUM,
	START_DATE, 
	CONCEPT_CD,
	ENCOUNTER_NUM,
	INSTANCE_NUM,
	NVAL_NUM, 
	TVAL_CHAR,
	VALTYPE_CD, 
	MODIFIER_CD,
	VALUEFLAG_CD, 
	PROVIDER_ID, 
	QUANTITY_NUM, 
	UNITS_CD, 
	END_DATE, 
	LOCATION_CD, 
	CONFIDENCE_NUM, 
	UPDATE_DATE, 
	DOWNLOAD_DATE, 
	IMPORT_DATE, 
	SOURCESYSTEM_CD, 
	UPLOAD_ID
)
;
CREATE INDEX FACT_CNPT_PAT_ENCT_IDX ON OBSERVATION_FACT
(CONCEPT_CD, INSTANCE_NUM, PATIENT_NUM, ENCOUNTER_NUM) 
;
CREATE INDEX FACT_PATCON_DATE_PRVD_IDX ON OBSERVATION_FACT
(PATIENT_NUM, CONCEPT_CD, START_DATE, END_DATE, ENCOUNTER_NUM, INSTANCE_NUM,
PROVIDER_ID, NVAL_NUM, VALTYPE_CD) 
;



-------------------------------------------------------------------
-- create PATIENT_DIMENSION table with clustered PK on PATIENT_NUM 
-------------------------------------------------------------------

CREATE TABLE PATIENT_DIMENSION ( 
	PATIENT_NUM      	NUMERIC(38,0) NOT NULL,
	VITAL_STATUS_CD  	VARCHAR(50) NULL,
	BIRTH_DATE       	TIMESTAMP WITHOUT TIME ZONE NULL,
	DEATH_DATE       	TIMESTAMP WITHOUT TIME ZONE NULL,
	SEX_CD           	VARCHAR(50) NULL,
	AGE_IN_YEARS_NUM 	NUMERIC(38,0) NULL,
	LANGUAGE_CD      	VARCHAR(50) NULL,
	RACE_CD          	VARCHAR(50) NULL,
	MARITAL_STATUS_CD	VARCHAR(50) NULL,
	RELIGION_CD      	VARCHAR(50) NULL,
	ZIP_CD           	VARCHAR(10) NULL,
	STATECITYZIP_PATH	VARCHAR(700) NULL,
	INCOME_CD			VARCHAR(50) NULL,
	PATIENT_BLOB     	TEXT NULL,
	UPDATE_DATE      	TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE    	TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE      	TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD  	VARCHAR(50) NULL,
	UPLOAD_ID        	NUMERIC(38,0) NULL,
    CONSTRAINT PATIENT_DIMENSION_PK PRIMARY KEY(PATIENT_NUM)
	)
;

-- add indexes on additional Patient_Dimension fields 
CREATE  INDEX PD_IDX_DATES ON PATIENT_DIMENSION(PATIENT_NUM, VITAL_STATUS_CD, BIRTH_DATE, DEATH_DATE)
;
CREATE  INDEX PD_IDX_AllPatientDim ON PATIENT_DIMENSION(PATIENT_NUM, VITAL_STATUS_CD, BIRTH_DATE, DEATH_DATE, SEX_CD, AGE_IN_YEARS_NUM, LANGUAGE_CD, RACE_CD, MARITAL_STATUS_CD, RELIGION_CD, ZIP_CD, INCOME_CD)
;
CREATE  INDEX PD_IDX_StateCityZip ON PATIENT_DIMENSION (STATECITYZIP_PATH, PATIENT_NUM)
;
CREATE INDEX PATD_UPLOADID_IDX ON PATIENT_DIMENSION(UPLOAD_ID)
;



-----------------------------------------------------------------------------------
-- create PROVIDER_DIMENSION table with clustered PK on PROVIDER_PATH, PROVIDER_ID 
-----------------------------------------------------------------------------------

CREATE TABLE PROVIDER_DIMENSION ( 
	PROVIDER_ID         VARCHAR(50) NOT NULL,
	PROVIDER_PATH       VARCHAR(700) NOT NULL,
	NAME_CHAR       	VARCHAR(850) NULL,
	PROVIDER_BLOB       TEXT NULL,
	UPDATE_DATE     	TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE       TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE         TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD     VARCHAR(50) NULL,
	UPLOAD_ID        	NUMERIC(38,0) NULL,
    CONSTRAINT  PROVIDER_DIMENSION_PK PRIMARY KEY(PROVIDER_PATH,PROVIDER_ID)
	)
;

-- add index on provider_id, name_char 
CREATE INDEX PD_IDX_NAME_CHAR ON PROVIDER_DIMENSION(PROVIDER_ID,NAME_CHAR)
;
CREATE INDEX PROD_UPLOADID_IDX ON PROVIDER_DIMENSION(UPLOAD_ID)
;



-------------------------------------------------------------------
-- create VISIT_DIMENSION table with clustered PK on ENCOUNTER_NUM 
-------------------------------------------------------------------

CREATE TABLE VISIT_DIMENSION ( 
	ENCOUNTER_NUM       NUMERIC(38,0) NOT NULL,
	PATIENT_NUM         NUMERIC(38,0) NOT NULL,
    ACTIVE_STATUS_CD    VARCHAR(50) NULL,
	START_DATE          TIMESTAMP WITHOUT TIME ZONE NULL,
	END_DATE            TIMESTAMP WITHOUT TIME ZONE NULL,
	INOUT_CD            VARCHAR(50) NULL,
	LOCATION_CD         VARCHAR(50) NULL,
	LOCATION_PATH  	    VARCHAR(900) NULL,
	LENGTH_OF_STAY      NUMERIC(38,0) NULL,
	VISIT_BLOB      	TEXT NULL,
	UPDATE_DATE         TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE       TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE         TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD     VARCHAR(50) NULL,
	UPLOAD_ID       	NUMERIC(38,0) NULL, 
    CONSTRAINT  VISIT_DIMENSION_PK PRIMARY KEY(ENCOUNTER_NUM,PATIENT_NUM)
	)
;

-- add indexes on addtional visit_dimension fields 
CREATE  INDEX VD_UPLOADID_IDX ON VISIT_DIMENSION(UPLOAD_ID)
;
CREATE INDEX VISITDIM_EN_PN_LP_IO_SD_IDX ON VISIT_DIMENSION
(ENCOUNTER_NUM, PATIENT_NUM, LOCATION_PATH, INOUT_CD, START_DATE,END_DATE, LENGTH_OF_STAY)
;
CREATE INDEX VISITDIM_STD_EDD_IDX ON VISIT_DIMENSION
(START_DATE, END_DATE)
;



------------------------------------------------------------
-- create MODIFIER_DIMENSION table with PK on MODIFIER_PATH 
------------------------------------------------------------

CREATE TABLE MODIFIER_DIMENSION ( 
	MODIFIER_PATH   	VARCHAR(700) NOT NULL,
	MODIFIER_CD     	VARCHAR(50) NULL,
	NAME_CHAR      		VARCHAR(2000) NULL,
	MODIFIER_BLOB   	TEXT NULL,
	UPDATE_DATE    		TIMESTAMP WITHOUT TIME ZONE NULL,
	DOWNLOAD_DATE  		TIMESTAMP WITHOUT TIME ZONE NULL,
	IMPORT_DATE    		TIMESTAMP WITHOUT TIME ZONE NULL,
	SOURCESYSTEM_CD		VARCHAR(50) NULL,
    UPLOAD_ID			NUMERIC (38,0) NULL,
    CONSTRAINT MODIFIER_DIMENSION_PK PRIMARY KEY(modifier_path)
	)
;
CREATE INDEX MD_IDX_UPLOADID ON MODIFIER_DIMENSION(UPLOAD_ID)
;





