
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from edu.harvard.i2b2.crc.loader.ejb.fr.FRBean
package edu.harvard.i2b2.crc.loader.ejb.fr;

/**
 * Local-Home interface for ejb.crc.loader.frbean
 */
public interface FRLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/ejb/crc/loader/frbeanLocal";
    public static final String JNDI_NAME = "ejb/crc/loader/frbeanLocal";

    edu.harvard.i2b2.crc.loader.ejb.fr.FRLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
